/* ============================================================
   Site languages (EN / 中文 / ES) — shared by index.html,
   projects.html and collaborators.html. See i18n.css and I18N.md.

   Every language has its own URL, so search engines index each one:
     /index.html          English (also the editable source: it holds all three languages)
     /zh/index.html       繁體中文  ┐ generated by tools/build_i18n.py,
     /es/index.html       Español   ┘ only their own language, <base href="../">
   <html data-page-lang> tells this script which version it is on.

   Load it in <head> (not deferred). On the English pages it may send
   a visitor to their language before first paint, first match wins:
     1. ?lang=zh|es|en in the URL (old links)
     2. the reader's own choice from clicking the switch (localStorage,
        under the blog's key, so 中文 here also means 中文 on the blog;
        the blog only has en/zh and shows English for "es")
     3. their region, from an IP lookup cached for 30 days:
        Taiwan / China / Hong Kong / Macau → 中文, Spain / Latin America → ES
     4. the browser language (zh* → 中文, es* → ES), when the lookup fails
     5. English
   The 中文 and Spanish URLs never redirect (someone asked for them),
   and crawlers are never redirected.
   On a first visit the English page stays hidden until the lookup
   answers (at most GEO_WAIT ms), so the language never visibly flips.

   Static text:    <span data-lang="en">…</span><span data-lang="zh">…</span><span data-lang="es">…</span>
   Generated text: SiteLang.t({ en, zh, es }) returns the same three spans.
   Page title/meta: data-zh="…" data-es="…" on <title> and the <meta> tags (used by the build).
   ============================================================ */
window.SiteLang = (function () {
  const KEY = 'wpc-blog-lang';          // manual choice, shared with the blog
  const GEO_KEY = 'wpc-geo-lang';       // { lang, t } from the IP lookup
  const GEO_URL = 'https://ipapi.co/country/';  // HTTPS, plain-text country code, free tier
  const GEO_TTL = 30 * 864e5, GEO_RETRY = 864e5, GEO_WAIT = 800;
  const REGION = {
    zh: ['TW', 'CN', 'HK', 'MO'],
    es: ['ES', 'MX', 'GT', 'SV', 'HN', 'NI', 'CR', 'PA', 'CU', 'DO', 'PR', 'CO', 'VE', 'EC', 'PE', 'BO', 'CL', 'AR', 'UY', 'PY', 'BR']
  };
  const BOT = /bot|crawl|spider|slurp|facebookexternalhit|embedly|preview|lighthouse/i;
  const LANGS = ['en', 'zh', 'es'];
  const HTML_LANG = { en: 'en', zh: 'zh-Hant', es: 'es' };
  const MONTHS_ES = ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'];
  const root = document.documentElement;
  const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  const valid = l => LANGS.includes(l);
  const PAGE = valid(root.getAttribute('data-page-lang')) ? root.getAttribute('data-page-lang') : 'en';
  const listeners = [];

  const store = (k, v) => { try { if (v === undefined) return localStorage.getItem(k); localStorage.setItem(k, v); } catch (e) {} };

  // Same page in another language. Generated pages have <base href="../">, so
  // relative URLs resolve against the site root on every version.
  function urlFor(lang) {
    const file = location.pathname.split('/').pop() || 'index.html';
    const u = new URL((lang === 'en' ? '' : lang + '/') + file, document.baseURI);
    const q = new URLSearchParams(location.search); q.delete('lang');
    u.search = q.toString(); u.hash = location.hash;
    return u.href;
  }
  function go(lang) { location.replace(urlFor(lang)); }

  function fromBrowser() {
    const l = String((navigator.languages && navigator.languages[0]) || navigator.language || '').toLowerCase();
    return l.startsWith('zh') ? 'zh' : l.startsWith('es') ? 'es' : 'en';
  }
  function fromCountry(cc) {
    cc = String(cc || '').trim().toUpperCase();
    return REGION.zh.includes(cc) ? 'zh' : REGION.es.includes(cc) ? 'es' : 'en';
  }
  function cachedGeo() {
    try {
      const g = JSON.parse(store(GEO_KEY) || 'null');
      if (g && valid(g.lang) && Date.now() < g.t) return g.lang;
    } catch (e) {}
    return null;
  }
  const cacheGeo = (lang, ttl) => store(GEO_KEY, JSON.stringify({ lang, t: Date.now() + ttl }));

  function detect() {
    root.classList.add('lang-pending');
    let done = false;
    const finish = (lang, ttl) => {
      if (done) return; done = true;
      if (ttl) cacheGeo(lang, ttl);
      // A click on the switch while waiting wins over the lookup.
      if (lang !== 'en' && !valid(store(KEY))) return go(lang);
      root.classList.remove('lang-pending');
    };
    // Shown if the lookup is slow or blocked; not cached, so a late answer still counts next time.
    setTimeout(() => finish(fromBrowser()), GEO_WAIT);
    const ctl = window.AbortController ? new AbortController() : null;
    if (ctl) setTimeout(() => ctl.abort(), 5000);
    fetch(GEO_URL, { signal: ctl && ctl.signal, credentials: 'omit' })
      .then(r => r.ok ? r.text() : Promise.reject(r.status))
      .then(cc => {
        if (!/^[A-Za-z]{2}$/.test(cc.trim())) throw cc;
        done ? cacheGeo(fromCountry(cc), GEO_TTL) : finish(fromCountry(cc), GEO_TTL);
      })
      // Lookup failed (offline, rate limit, blocker): use the browser language for a day, then try again.
      .catch(() => { done ? cacheGeo(fromBrowser(), GEO_RETRY) : finish(fromBrowser(), GEO_RETRY); });
  }

  // Runs now, in <head>, before first paint.
  root.setAttribute('data-reading', PAGE);
  (function route() {
    const q = new URLSearchParams(location.search).get('lang');
    if (valid(q)) return q !== PAGE && go(q);       // an old ?lang= link: it is what the reader asked for
    if (PAGE !== 'en' || BOT.test(navigator.userAgent)) return;
    const own = store(KEY);
    if (valid(own)) return own !== 'en' && go(own);
    const geo = cachedGeo();
    if (geo) return geo !== 'en' && go(geo);
    detect();
  })();

  // The blog only has en/zh and reads ?lang=, so pass this page's language along (Spanish → English).
  function syncBlogLinks() {
    document.querySelectorAll('a[href^="blog"]').forEach(a => {
      const [path, hash] = a.getAttribute('href').split('#');
      a.setAttribute('href', path.split('?')[0] + '?lang=' + (PAGE === 'zh' ? 'zh' : 'en') + (hash ? '#' + hash : ''));
    });
  }

  function init() {
    document.querySelectorAll('[data-set-lang]').forEach(b => {
      b.setAttribute('aria-pressed', String(b.dataset.setLang === PAGE));
      b.addEventListener('click', () => {
        const lang = b.dataset.setLang;
        store(KEY, lang);                      // every click counts as the reader's own choice
        if (lang !== PAGE) location.href = urlFor(lang);
      });
    });
    syncBlogLinks();
    listeners.forEach(fn => fn(PAGE));
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();

  return {
    get: () => PAGE,
    onChange(fn) { listeners.push(fn); },
    // Pick the string for the page language from { en, zh, es } (falls back to English).
    pick(map, lang) { lang = lang || PAGE; return map == null ? '' : typeof map === 'string' ? map : (map[lang] ?? map.en); },
    // Render { en, zh, es } as three language spans; CSS shows the active one.
    // Values are escaped unless html is true.
    t(map, html) {
      if (map == null) return '';
      if (typeof map === 'string') return html ? map : esc(map);
      return LANGS.map(l => {
        const v = map[l] ?? map.en;
        return '<span data-lang="' + l + '" lang="' + HTML_LANG[l] + '">' + (html ? v : esc(v)) + '</span>';
      }).join('');
    },
    // Dates: "YYYY-MM-DD" or "YYYY-MM" → "April 9, 2026" / "2026 年 4 月 9 日" / "9 de abril de 2026".
    date(iso, lang) {
      const [y, m, d] = String(iso).split('-').map(Number);
      if (lang === 'zh') return y + ' 年 ' + m + ' 月' + (d ? ' ' + d + ' 日' : '');
      if (lang === 'es') return (d ? d + ' de ' : '') + MONTHS_ES[m - 1] + ' de ' + y;
      const opts = d ? { year: 'numeric', month: 'long', day: 'numeric' } : { year: 'numeric', month: 'long' };
      return new Date(y, m - 1, d || 1).toLocaleDateString('en-US', opts);
    },
    esc
  };
})();
